### ISSUE TITLE
Screenshot only captures default view, instead of view of user.

### ISSUE THREAD

**Issue by teluskevinliang** [fochlac/mui-feedback-dialog#4]
When taking screenshot of a webpage that has (say vertical) scrolling, screenshot will only capture initial view (top part of page). Thus leaving web-content outside of the screen (bottom half) to be left uncaptured.

Solution: Capture screenshot where user is currently at. For example, bottom of the web page.

**Comment by teluskevinliang** [comment]
Hey fochlac, thanks for creating this widget!

**Comment by fochlac** [comment]
Hi, this is an issue that has not yet been fixed in the underlying library: https://github.com/1904labs/dom-to-image-more/issues/22 or https://github.com/bubkoo/html-to-image/pull/209
The only solution I see would be to use the screen-capture variant.

**Comment by thomascreveaux** [comment]
Hello @fochlac. Thank you for your work. It seems that the issue related to html-image library has been fixed (see https://github.com/bubkoo/html-to-image/pull/209). I guess there is something more to do because this does not seem to fix the issue in you library.

**Comment by fochlac** [comment]
It's indeed fixed in this fork: https://github.com/qq15725/modern-screenshot, so I switched to it. The position of the scroll bar is still off, but the correct content is shown at least.
